<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        if (! Schema::hasTable('colegio')) {
            Schema::create('colegio', function (Blueprint $table): void {
                $table->char('colegio', 40);
                $table->char('dir1', 40);
                $table->char('dir2', 40);
                $table->char('pueblo1', 20);
                $table->char('esta1', 4);
                $table->char('zip1', 12);
                $table->char('dir3', 40);
                $table->char('dir4', 40);
                $table->char('pueblo2', 20);
                $table->char('esta2', 4);
                $table->char('zip2', 12);
                $table->char('correo', 40);
                $table->char('telefono', 13);
                $table->char('fax', 13);
                $table->string('logo', 2);
                $table->string('foto', 2);
                $table->char('director', 35);
                $table->char('usuario', 20)->unique('usuario');
                $table->char('clave', 20);
                $table->char('principal', 35);
                $table->char('pagina', 35);
                $table->char('idioma', 3);
                $table->char('filename', 50);
                $table->char('filename2', 50);
                $table->char('filesize', 50);
                $table->char('filesize2', 50);
                $table->char('filetype', 50);
                $table->char('filetype2', 50);
                $table->char('description', 50);
                $table->date('ft1');
                $table->date('ft2');
                $table->date('ft3');
                $table->date('ft4');
                $table->date('ft5');
                $table->date('ft6');
                $table->date('ft7');
                $table->date('ft8');
                $table->mediumText('men_ini');
                $table->mediumText('men_nota');
                $table->char('grupo', 15);
                $table->char('activo', 10);
                $table->date('ufecha');
                $table->char('id', 7)->unique('id');
                $table->char('year', 5);
                $table->char('Colegio2', 40);
                $table->char('dir5', 40);
                $table->char('dir6', 40);
                $table->char('pueblo3', 20);
                $table->char('est3', 4);
                $table->char('zip3', 12);
                $table->char('tel3', 13);
                $table->char('tel4', 13);
                $table->char('pag_ini2', 5);
                $table->char('fax2', 13);
                $table->char('email3', 50);
                $table->char('email4', 50);
                $table->char('a', 4);
                $table->char('b', 4);
                $table->char('c', 4);
                $table->char('d', 4);
                $table->char('f', 4);
                $table->char('sutri', 10);
                $table->char('vala', 3);
                $table->char('valb', 3);
                $table->char('valc', 3);
                $table->char('vald', 3);
                $table->char('valf', 3);
                $table->char('sie', 2);
                $table->char('sieab', 1);
                $table->char('asist', 2);
                $table->char('asis', 1);
                $table->char('curso', 4);
                $table->char('por1', 3);
                $table->char('por2', 3);
                $table->char('por3', 3);
                $table->char('cv', 2);
                $table->char('np', 2);
                $table->char('teg', 3);
                $table->char('tr1', 2);
                $table->char('tr2', 2);
                $table->char('tr3', 2);
                $table->char('tr4', 2);
                $table->char('vt1', 2);
                $table->char('vt2', 2);
                $table->char('vt3', 2);
                $table->char('vt4', 2);
                $table->char('email5', 50);
                $table->char('cm', 2);
                $table->char('tpa', 2);
                $table->char('nin', 2);
                $table->char('tarjeta', 2);
                $table->char('forzar', 2);
                $table->char('clavepadre', 20);
                $table->mediumText('nivel');
                $table->date('fechav1');
                $table->date('fechav2');
                $table->char('nota', 1);
                $table->char('prom', 3);
                $table->char('cant', 2);
                $table->char('sem', 2);
                $table->char('nota2', 2);
                $table->char('prom2', 3);
                $table->char('cant2', 2);
                $table->char('sem2', 2);
                $table->char('nota3', 2);
                $table->char('prom3', 3);
                $table->char('cant3', 2);
                $table->char('sem3', 2);
                $table->char('bo1', 2);
                $table->char('bo2', 2);
                $table->char('bo3', 2);
                $table->char('bo4', 2);
                $table->mediumText('mensa');
                $table->string('tar', 10);
                $table->mediumText('men_inac');
                $table->string('inactivo', 2);
                $table->char('year2', 5);
                $table->char('vs1', 2);
                $table->char('vs2', 2);
                $table->char('vf', 2);
                $table->char('ns1', 2);
                $table->char('ns2', 2);
                $table->char('nf', 2);
                $table->string('bloqueo', 2);
                $table->string('codigo', 25);
                $table->string('bloqueoauto', 2);
                $table->string('des1', 25);
                $table->string('des2', 25);
                $table->string('des3', 25);
                $table->string('controlb', 15);
                $table->mediumText('param1');
                $table->mediumText('param2');
                $table->mediumText('param3');
                $table->mediumText('param4');
                $table->mediumText('param5');
                $table->mediumText('param6');
                $table->float('esn', 7);
                $table->string('esncodigo', 5);
                $table->string('esnmes', 2);
                $table->string('act_paypal', 2);
                $table->string('email_paypal', 70);
                $table->float('costo', 4);
                $table->integer('caja');
                $table->string('rec', 1);
                $table->date('asis1');
                $table->date('asis2');
                $table->date('asis3');
                $table->date('asis4');
                $table->date('asis5');
                $table->date('asis6');
                $table->date('asis7');
                $table->date('asis8');
                $table->string('clave_email', 30);
                $table->string('host_smtp', 30);
                $table->integer('port');
                $table->string('email_smtp', 50);
                $table->string('host', 2);
                $table->integer('tri');
                $table->date('fec_t');
                $table->string('se1', 2);
                $table->string('se2', 2);
                $table->string('fin', 2);
                $table->string('paypalcodigo', 7);
                $table->string('enf', 2);
                $table->string('nmf', 3);
                $table->integer('dia_vence');
                $table->string('etd', 2);
                $table->string('npn', 2);
                $table->string('cppd', 2);
                $table->string('codc1', 2);
                $table->float('codc2', 7);
                $table->string('suantri', 2);
                $table->string('nel', 2);
                $table->string('chk', 5);
                $table->string('not1', 100);
                $table->string('not2', 100);
                $table->integer('fra');
                $table->string('vnf', 2);
                $table->string('hdp', 2);
                $table->integer('hdt');
                $table->text('token_whatsapp')->nullable();
                $table->string('cel_whatsapp', 10)->nullable();
                $table->text('rema_msg')->nullable();
                $table->float('can_min', 7);
                $table->string('ip7', 20);
                $table->string('fecha7', 20);
                $table->string('hora7', 20);
                $table->json('environments')->nullable();
                $table->json('constants')->nullable();
                $table->string('esac', 2);
                $table->string('camisas', 2);
                $table->string('cena', 2);
                $table->string('actinf', 2);
                $table->string('actmat', 2);
                $table->string('actmen', 2);
                $table->string('actfotos', 2);
                $table->integer('es1');
                $table->integer('es2');
                $table->integer('es3');
                $table->integer('es4');
                $table->integer('es5');
                $table->integer('es6');
                $table->integer('es7');
                $table->integer('es8');
                $table->integer('es9');
                $table->string('cta_camisa', 7);
                $table->string('es_ac', 2);
            });
        }
    }
};
