interface Grade {
  id: string;
  curso: string;
  year: string;
  descripcion: string;
  credito: number;
  peso: number;
  entrada: string;
  salida: string;
  dias: string;
  maestro: string;
  matri: number;
  total: number;
  ava: string;
  valor: number;
  orden: string;
  verano: string;
  mt: number;
}
export interface Teacher {
  grados?: Grade[];
  id: number;
  nombre: string;
  apellidos: string;
  nombre_completo: string;
  ss: string;
  tel_res: string;
  tel_emer: string;
  cel: string;
  posicion: string;
  genero: string;
  fecha_nac: string;
  fecha_ini: string;
  fecha_daja: string;
  nivel: string | null;
  preparacion1: string | null;
  preparacion2: string | null;
  grado: string | null;
  email1: string;
  email2: string | null;
  dir1: string;
  dir2: string;
  pueblo1: string;
  esta1: string;
  zip1: string;
  dir3: string;
  dir4: string;
  pueblo2: string;
  esta2: string;
  zip2: string;
  club1: string | null;
  club2: string | null;
  club3: string | null;
  club4: string | null;
  club5: string | null;
  usuario: string;
  clave: string;
  tipo: string;
  foto: Blob;
  grupo: string;
  activo: string;
  idioma: string;
  ufecha: string;
  re_e: string;
  year: string;
  cel_com: string;
  alias: string | null;
  baja: string;
  pre1: string | null;
  pre2: string | null;
  pre3: string | null;
  pre4: string | null;
  pre5: string | null;
  vi1: string | null;
  vi2: string | null;
  vi3: string | null;
  vi4: string | null;
  vi5: string | null;
  se1: string | null;
  se2: string | null;
  se3: string | null;
  se4: string | null;
  se5: string | null;
  comp: string;
  lic1: string | null;
  lic2: string | null;
  lic3: string | null;
  lic4: string | null;
  lp1: string | null;
  lp2: string | null;
  lp3: string | null;
  lp4: string | null;
  fex1: string | null;
  fex2: string | null;
  fex3: string | null;
  fex4: string | null;
  pe1: string | null;
  pe2: string | null;
  pe3: string | null;
  pe4: string | null;
  pe5: string | null;
  pe6: string | null;
  pe7: string | null;
  pe8: string | null;
  dep: number;
  dep_des: string;
  docente: string;
  foto_name: string;
  email_smtp: string;
  clave_email: string;
  host_smtp: string;
  port: number;
  host: string;
  tipo_foro: number;
  avatar: string;
  fechas: number;
  tri: number | null;
  pe9: string | null;
  pe10: string | null;
  pe11: string | null;
  pe12: string | null;
  pe13: string | null;
  pe14: string | null;
  pe15: string | null;
  pe16: string | null;
  cbarra: string | null;
}
