/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "filament.exports.download": [
        {
            "name": "export",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.imports.failed-rows.download": [
        {
            "name": "import",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.admin.auth.login": [],
    "filament.admin.auth.logout": [],
    "filament.admin.pages.dashboard": [],
    "filament.admin.resources.configurations.index": [],
    "filament.admin.resources.features.index": [],
    "filament.admin.resources.schools.index": [],
    "filament.admin.resources.schools.create": [],
    "filament.admin.resources.schools.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.users.index": [],
    "sanctum.csrf-cookie": [],
    "telescope": [
        {
            "name": "view",
            "required": false
        }
    ],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "resend.webhook": [],
    "stancl.tenancy.asset": [
        {
            "name": "path",
            "required": false
        }
    ],
    "mailbook.dashboard": [
        {
            "name": "school",
            "required": true
        }
    ],
    "mailbook.content": [
        {
            "name": "school",
            "required": true
        }
    ],
    "mailbook.send": [
        {
            "name": "school",
            "required": true
        }
    ],
    "home": [],
    "contact.index": [],
    "contact.submit": [],
    "modules": [],
    "regiweb": [],
    "home.index": [
        {
            "name": "school",
            "required": true
        }
    ],
    "home.documents": [
        {
            "name": "school",
            "required": true
        }
    ],
    "home.documents.download": [
        {
            "name": "school",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.login.index": [
        {
            "name": "school",
            "required": true
        }
    ],
    "admin.login": [
        {
            "name": "school",
            "required": true
        }
    ],
    "admin.logout": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.login.index": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.login": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.logout": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.password": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.index": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.home": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.profile.show": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.profile.update": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.notes.index": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.notes.show": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.notes.default.save": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.notes.attendance.save": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.notes.exam.save": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.notes.values.save": [
        {
            "name": "school",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "regiweb.notes.attendance.entry": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.notes.attendance.entry.update": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.notes.attendance.report": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.notes.attendance.dailyReport": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.options.index": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.options.messages.email.index": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.options.messages.email.form": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.options.messages.email.send": [
        {
            "name": "school",
            "required": true
        }
    ],
    "regiweb.reports.index": [
        {
            "name": "school",
            "required": true
        }
    ],
    "parents.login.index": [
        {
            "name": "school",
            "required": true
        }
    ],
    "parents.login": [
        {
            "name": "school",
            "required": true
        }
    ],
    "parents.logout": [
        {
            "name": "school",
            "required": true
        }
    ],
    "foro.teacher.login.index": [
        {
            "name": "school",
            "required": true
        }
    ],
    "foro.teacher.login": [
        {
            "name": "school",
            "required": true
        }
    ],
    "foro.teacher.logout": [
        {
            "name": "school",
            "required": true
        }
    ],
    "foro.student.login.index": [
        {
            "name": "school",
            "required": true
        }
    ],
    "foro.student.login": [
        {
            "name": "school",
            "required": true
        }
    ],
    "foro.student.logout": [
        {
            "name": "school",
            "required": true
        }
    ]
}
}
export {};
