<?php

declare(strict_types=1);

namespace App\Http\Resources\Student;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

final class StudentGradeResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'padre' => $this->padre,
            'madre' => $this->madre,
            'nombre' => $this->nombre,
            'apellidos' => $this->apellidos,
            'descripcion' => $this->descripcion,
            'grado' => $this->grado,
            'curso' => $this->curso,
            'profesor' => $this->profesor,
            'hora' => $this->hora,
            'dias' => $this->dias,
            'nota1' => $this->nota1,
            'nota2' => $this->nota2,
            'nota3' => $this->nota3,
            'nota4' => $this->nota4,
            'con1' => $this->con1,
            'con2' => $this->con2,
            'con3' => $this->con3,
            'con4' => $this->con4,
            'sem1' => $this->sem1,
            'sem2' => $this->sem2,
            'credito' => $this->credito,
            'final' => $this->final,
            'usuario' => $this->usuario,
            'clave' => $this->clave,
            'desc2' => $this->desc2,
            'email' => $this->email,
            'idioma' => $this->idioma,
            'not1' => $this->not1,
            'not2' => $this->not2,
            'not3' => $this->not3,
            'not4' => $this->not4,
            'not5' => $this->not5,
            'not6' => $this->not6,
            'not7' => $this->not7,
            'not8' => $this->not8,
            'not9' => $this->not9,
            'not10' => $this->not10,
            'not11' => $this->not11,
            'not12' => $this->not12,
            'not13' => $this->not13,
            'not14' => $this->not14,
            'not15' => $this->not15,
            'not16' => $this->not16,
            'not17' => $this->not17,
            'not18' => $this->not18,
            'not19' => $this->not19,
            'not20' => $this->not20,
            'tpa1' => $this->tpa1,
            'tpa2' => $this->tpa2,
            'tpa3' => $this->tpa3,
            'tpa4' => $this->tpa4,
            'por1' => $this->por1,
            'por2' => $this->por2,
            'por3' => $this->por3,
            'por4' => $this->por4,
            'ss' => $this->ss,
            'not21' => $this->not21,
            'not22' => $this->not22,
            'not23' => $this->not23,
            'not24' => $this->not24,
            'not25' => $this->not25,
            'not26' => $this->not26,
            'not27' => $this->not27,
            'not28' => $this->not28,
            'not29' => $this->not29,
            'not30' => $this->not30,
            'not31' => $this->not31,
            'not32' => $this->not32,
            'not33' => $this->not33,
            'not34' => $this->not34,
            'not35' => $this->not35,
            'not36' => $this->not36,
            'not37' => $this->not37,
            'not38' => $this->not38,
            'not39' => $this->not39,
            'not40' => $this->not40,
            'letra' => $this->letra,
            'aus1' => $this->aus1,
            'aus2' => $this->aus2,
            'aus3' => $this->aus3,
            'aus4' => $this->aus4,
            'tar1' => $this->tar1,
            'tar2' => $this->tar2,
            'tar3' => $this->tar3,
            'tar4' => $this->tar4,
            'tl1' => $this->tl1,
            'tl2' => $this->tl2,
            'tl3' => $this->tl3,
            'tl4' => $this->tl4,
            'td1' => $this->td1,
            'td2' => $this->td2,
            'td3' => $this->td3,
            'td4' => $this->td4,
            'year' => $this->year,
            'id2' => $this->id2,
            'nota_por' => $this->nota_por,
            'ptd1' => $this->ptd1,
            'ptd2' => $this->ptd2,
            'ptd3' => $this->ptd3,
            'ptd4' => $this->ptd4,
            'ptl1' => $this->ptl1,
            'ptl2' => $this->ptl2,
            'ptl3' => $this->ptl3,
            'ptl4' => $this->ptl4,
            'pal' => $this->pal,
            'sutri' => $this->sutri,
            'sie1' => $this->sie1,
            'sie2' => $this->sie2,
            'sie3' => $this->sie3,
            'sie4' => $this->sie4,
            'sie5' => $this->sie5,
            'sie6' => $this->sie6,
            'sie7' => $this->sie7,
            'sie8' => $this->sie8,
            'pc1' => $this->pc1,
            'pc2' => $this->pc2,
            'pc3' => $this->pc3,
            'pc4' => $this->pc4,
            'tpc1' => $this->tpc1,
            'tpc2' => $this->tpc2,
            'tpc3' => $this->tpc3,
            'tpc4' => $this->tpc4,
            'control' => $this->control,
            'ex1' => $this->ex1,
            'ex2' => $this->ex2,
            'de1' => $this->de1,
            'de2' => $this->de2,
            'de3' => $this->de3,
            'de4' => $this->de4,
            'com1' => $this->com1,
            'com2' => $this->com2,
            'com3' => $this->com3,
            'com4' => $this->com4,
            'verano' => $this->verano,
            'baja' => $this->baja,
            'orden' => $this->orden,
            'ava' => $this->ava,
            'valor' => $this->valor,
            'aa' => $this->aa,
            'average1' => $this->average1,
            'average2' => $this->average2,
            'average3' => $this->average3,
            'average4' => $this->average4,
            'peso' => $this->peso,
        ];
    }
}
